class_name MeleeWeapons extends MechWeapon

class ChargedBlade extends MeleeWeapons:
	func _init() -> void:
		name = "Charged Blade"
		abbreviation = "Ch. Blade"
		requiredmount = Enums.MountType.MAIN
		type = Enums.WeaponType.MELEE
		damage = [[Enums.DamageType.ENERGY, Die.new(1,3), 3]]
		wrange = {Enums.RangeType.THREAT:1}
		tags = [Tag.ArmorPiercing.new()]
		source = "GMS"
		license = "GMS 0"
		license_level = 0
		capacity = 2
		description = "Much like GMS mechs, GMS weapons are reliable galactic standards, made using interchangeable parts and built to withstand almost any conditions. There are three lines currently in production. The Type-II (T-2) line displays GMS’s proprietary “charged” melee weapons and energy weapons. T-2 charged melee weapons are structurally similar to GMS’s T-1 melee weapons, though built with different materials to tolerate the intense heat generated by their projected plasma sheaths. These sheaths can be toggled on or off, depending on the needs of the pilot. GMS’s T-2 energy weapons, like their T-1 kinetics, are sturdy tools with predictable power scaling, minimal particle scattering, and consistent performance ranges. They feature universal ports allowing them to accept a variety of power sources, from hardline cabling through to “magazine” style power packs."

class HeavyChargedBlade extends MeleeWeapons:
	func _init() -> void:
		name = "Heavy Charged Blade"
		abbreviation = "Heavy Ch."
		requiredmount = Enums.MountType.HEAVY
		type = Enums.WeaponType.MELEE
		damage = [[Enums.DamageType.ENERGY, Die.new(1,6), 3]]
		wrange = {Enums.RangeType.THREAT:1}
		tags = [Tag.ArmorPiercing.new()]
		source = "GMS"
		license = "GMS 0"
		license_level = 0
		capacity = 3
		description = "Much like GMS mechs, GMS weapons are reliable galactic standards, made using interchangeable parts and built to withstand almost any conditions. There are three lines currently in production. The Type-II (T-2) line displays GMS’s proprietary “charged” melee weapons and energy weapons. T-2 charged melee weapons are structurally similar to GMS’s T-1 melee weapons, though built with different materials to tolerate the intense heat generated by their projected plasma sheaths. These sheaths can be toggled on or off, depending on the needs of the pilot. GMS’s T-2 energy weapons, like their T-1 kinetics, are sturdy tools with predictable power scaling, minimal particle scattering, and consistent performance ranges. They feature universal ports allowing them to accept a variety of power sources, from hardline cabling through to “magazine” style power packs."

class HeavyMeleeWeapon extends MeleeWeapons:
	func _init() -> void:
		name = "Heavy Melee Weapon"
		abbreviation = "Heavy MW"
		requiredmount = Enums.MountType.HEAVY
		type = Enums.WeaponType.MELEE
		damage = [[Enums.DamageType.KINETIC, Die.new(2,6), 1]]
		wrange = {Enums.RangeType.THREAT:1}
		tags = []
		source = "GMS"
		license = "GMS 0"
		license_level = 0
		capacity = 3
		description = "Much like GMS mechs, GMS weapons are reliable galactic standards, made using interchangeable parts and built to withstand almost any conditions. There are three lines currently in production. The Type-I (T-1) line is defined by powerful, reliable, and conventional-kinetic ranged and melee weapons, including the GMS assault rifle, heavy machine gun, shotgun, pistol, and various light and heavy blades. Reliable galactic standards, the GMS T-1 line is the most widely used mech-scale line of weaponry across the galaxy. Echoing the Everest’s design notes, T-1 weapons are simply designed, with few (if any) moving parts, intended to be used in or adaptable to any environment."

class SegmentKnife extends MeleeWeapons:
	func _init() -> void:
		name = "Segment Knife"
		abbreviation = "Seg. Knife"
		requiredmount = Enums.MountType.AUX
		type = Enums.WeaponType.MELEE
		damage = [[Enums.DamageType.ENERGY, Die.new(1,3), 1]]
		wrange = {Enums.RangeType.THREAT:1}
		tags = [Tag.Overkill.new()]
		source = "GMS"
		license = "GMS 0"
		license_level = 0
		capacity = 1
		description = "The fearsome “segment knife” is a system that uses flash-printing to produce disposable edged weapons in a vicinity around the user."

class TacticalKnife extends MeleeWeapons:
	func _init() -> void:
		name = "Tactical Knife"
		abbreviation = "Tac. Knife"
		requiredmount = Enums.MountType.AUX
		type = Enums.WeaponType.MELEE
		damage = [[Enums.DamageType.KINETIC, Die.new(1,3), 1]]
		wrange = {Enums.RangeType.THREAT:1}
		tags = [Tag.Thrown.new(3)]
		source = "GMS"
		license = "GMS 0"
		license_level = 0
		capacity = 1
		description = "Much like GMS mechs, GMS weapons are reliable galactic standards, made using interchangeable parts and built to withstand almost any conditions. There are three lines currently in production. The Type-I (T-1) line is defined by powerful, reliable, and conventional-kinetic ranged and melee weapons, including the GMS assault rifle, heavy machine gun, shotgun, pistol, and various light and heavy blades. Reliable galactic standards, the GMS T-1 line is the most widely used mech-scale line of weaponry across the galaxy. Echoing the Everest’s design notes, T-1 weapons are simply designed, with few (if any) moving parts, intended to be used in or adaptable to any environment."

class TacticalMeleeWeapon extends MeleeWeapons:
	func _init() -> void:
		name = "Tactical Melee Weapon"
		abbreviation = "Tac. MW"
		requiredmount = Enums.MountType.MAIN
		type = Enums.WeaponType.MELEE
		damage = [[Enums.DamageType.KINETIC, Die.new(1,6), 2]]
		wrange = {Enums.RangeType.THREAT:1}
		tags = [Tag.Thrown.new(3)]
		source = "GMS"
		license = "GMS 0"
		license_level = 0
		capacity = 2
		description = "Much like GMS mechs, GMS weapons are reliable galactic standards, made using interchangeable parts and built to withstand almost any conditions. There are three lines currently in production. The Type-I (T-1) line is defined by powerful, reliable, and conventional-kinetic ranged and melee weapons, including the GMS assault rifle, heavy machine gun, shotgun, pistol, and various light and heavy blades. Reliable galactic standards, the GMS T-1 line is the most widely used mech-scale line of weaponry across the galaxy. Echoing the Everest’s design notes, T-1 weapons are simply designed, with few (if any) moving parts, intended to be used in or adaptable to any environment."

class TempestChargedBlade extends MeleeWeapons:
	func _init() -> void:
		name = "Tempest Charged Blade"
		abbreviation = "Tempest CB"
		requiredmount = Enums.MountType.SUPERHEAVY
		type = Enums.WeaponType.MELEE
		damage = [[Enums.DamageType.ENERGY, Die.new(3,6), 4]]
		wrange = {Enums.RangeType.THREAT:2}
		tags = [Tag.ArmorPiercing.new(), Tag.Knockback.new(2)]
		source = "GMS"
		license = "GMS 0"
		license_level = 0
		capacity = 3
		description = "The latest innovations of GMS’s Type-II line of powered and energy weapons have produced a charged blade of staggering proportions. It is currently carried in the “Storm” line of superheavy equipment."
